spring:
  datasource:
    url: jdbc:oracle:${DB_PROD_SERVER:thin:@oracle.fiap.com.br}:${DB_PROD_PORT:1521}:${DB_PROD_NAME:ORCL}
    username: ${DB_HOMOLOG_USERNAME:X}
    password: ${DB_HOMOLOG_PASSWORD:x}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true