spring:
  datasource:
    url: jdbc:oracle:${DB_HOMOLOG_SERVER:thin:@oracle.fiap.com.br}:${DB_HOMOLOG_PORT:1521}:${DB_HOMOLOG_NAME:ORCL}
    username: ${DB_HOMOLOG_USERNAME:pf1646}
    password: ${DB_HOMOLOG_PASSWORD:fiap23}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true