spring:
  datasource:
    url: jdbc:oracle:${DB_PROD_SERVER:thin:@oracle.fiap.com.br}:${DB_PROD_PORT:1521}:${DB_PROD_NAME:ORCL}
    username: ${DB_PROD_USERNAME:xxxx}
    password: ${DB_PROD_PASSWORD:xxxx}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true