spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_URL:localhost}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:desenvolvimento-benezinho-pizzaria-2TDSPJ}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME:root}
    password: ${DB_DESENV_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
